language: python
python:
  - "3.7-dev"
services:
  - postgresql
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=''
    - PGHOST=localhost
install:
  - pip install -r requirements.txt
before_script:
  - sudo apt-get install postgresql postgresql-contrib
  - sudo apt-get install postgis
  - sleep 5
  - sudo service postgresql status 10
  - psql -c 'create database college_housing_db;' -U postgres
  - psql -U postgres -c "create extension postgis" -d college_housing_db
  - python manage.py makemigrations colleges housing tags

script:
  -python test_fiile.py