# Generated by Django 2.1.4 on 2018-12-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='housing.Housing')),
            ],
        ),
    ]
